# Generated by Django 5.1.1 on 2024-10-20 15:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Skechers', 'Skechers'), ('Crocs', 'Crocs'), ('SinPauk', 'SinPauk'), ('Timberland', 'Timberland')], max_length=40)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=1)),
                ('type', models.CharField(choices=[('Running', 'Running'), ('Basketball', 'Basketball'), ('Skateboarding', 'Skateboarding'), ('Training', 'Training'), ('Football', 'Football'), ('Lifestyle', 'Lifestyle')], max_length=20)),
                ('color', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Pink', 'Pink'), ('Orange', 'Orange'), ('Cyan', 'Cyan'), ('Yellow', 'Yellow')], max_length=20)),
                ('price', models.FloatField()),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(upload_to='shoe_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shoes')),
            ],
            options={
                'unique_together': {('user', 'shoe')},
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shoes')),
            ],
            options={
                'unique_together': {('user', 'shoe')},
            },
        ),
    ]
